#ItemSounds by Dyukusi( dyukusin@gmail.com )
#Special Thanks : Rieno

#default(undefined in this config) equip armor sound setting( sound, volume, pitch )
default_equip_armor_sound: HORSE_ARMOR,1,0.7

#equip armor sound setting( material, sound, volume, pitch )
equip_armor_sounds:
  - DIAMOND_HELMET,ZOMBIE_METAL,1,0.9  
  - DIAMOND_CHESTPLATE,ZOMBIE_METAL,1,0.5
  - DIAMOND_LEGGINGS,ZOMBIE_METAL,1,0.6
  - DIAMOND_BOOTS,ZOMBIE_METAL,1,0.8
  
######################################################################################

#default(undefined in this config) equip handitem sound setting( sound, volume, pitch )
default_equip_handitem_sound: NOTE_STICKS,1,0.8

#equip item in quickbar sound setting( material, sound, volume, pitch )
equip_handitem_sounds:
  - DIAMOND_SWORD,ANVIL_LAND,1,1.5
  - DIRT,DIG_GRASS,1,0.8
  
  
######################################################################################

#default(undefined in this config) put item sound setting( sound, volume, pitch )
default_put_item_sound: NOTE_STICKS,1,0.5    

#put item in inventory sound setting( material, sound, volume, pitch )
put_item_sounds:
  - STONE,STEP_STONE,1,1.2
  - GRASS,DIG_GRASS,1,0.7
  - DIRT,DIG_GRASS,1,0.5
  - COBBLESTONE,DIG_GRAVEL,1,0.5
  - WOOD,WOOD_CLICK,1,1.5
  - BEDROCK,IRONGOLEM_WALK,1,0.5
  - SAND,DIG_SAND,1,1.5
  - GRAVEL,DIG_GRAVEL,1,1.2
  - GOLD_ORE,IRONGOLEM_WALK,1,1.3
  - IRON_ORE,IRONGOLEM_WALK,1,1.3
  - COAL_ORE,DIG_STONE,1,1.5
  - LOG,DIG_WOOD,1,1.2
  - SPONGE,IRONGOLEM_THROW,1,1.5
  - GLASS,GLASS,1,1.3
  - LAPIS_ORE,DIG_STONE,1,1.5
  - LAPIS_BLOCK,ITEM_BREAK,1,0.5
  - SANDSTONE,STEP_STONE,1,0.5
  - WOOL,DIG_WOOL,1,1.5
  - GOLD_BLOCK,ZOMBIE_METAL,1,0.5
  - IRON_BLOCK,ZOMBIE_METAL,1,0.5
  - STEP,STEP_STONE,1,1.2
  - BRICK,STEP_STONE,1,1.5
  - BOOKSHELF,ZOMBIE_WOOD,1,1.5
  - MOSSY_COBBLESTONE,DIG_GRAVEL,1,0.5
  - OBSIDIAN,IRONGOLEM_WALK,1,0.7
  - WOOD_STAIRS,WOOD_CLICK,1,1.5
  - DIAMOND_ORE,IRONGOLEM_WALK,1,1.5
  - DIAMOND_BLOCK,ZOMBIE_METAL,1,1.5
  - COBBLESTONE_STAIRS,DIG_GRAVEL,1,0.5
  - REDSTONE_ORE,DIG_STONE,1,1.5
  - ICE,GLASS,1,0.5
  - SNOW_BLOCK,DIG_SNOW,1,0.5
  - CLAY,STEP_SAND,1,0.7
  - PUMPKIN,STEP_WOOD,1,1.5
  - NETHERRACK,FALL_SMALL,1,1.2
  - SOUL_SAND,DIG_GRASS,1,1.5
  - GLOWSTONE,LEVEL_UP,1,0.6
  - JACK_O_LANTERN,STEP_WOOD,1,1.5
  - STAINED_GLASS,GLASS,1,1.3
  - SMOOTH_BRICK,STEP_STONE,1,0.7
  - MELON_BLOCK,STEP_WOOD,1,1.5
  - BRICK_STAIRS,STEP_STONE,1,1.5
  - SMOOTH_STAIRS,STEP_STONE,1,0.7
  - MYCEL,DIG_GRASS,1,1.2
  - NETHER_BRICK,DIG_STONE,1,0.5
  - NETHER_BRICK_STAIRS,DIG_STONE,1,0.5
  - ENDER_STONE,FALL_SMALL,1,1.5
  - WOOD_STEP,WOOD_CLICK,1,1.5
  - SANDSTONE_STAIRS,STEP_STONE,1,0.5
  - EMERALD_ORE,IRONGOLEM_WALK,1,1.3
  - EMERALD_BLOCK,ZOMBIE_METAL,1,0.5
  - SPRUCE_WOOD_STAIRS,WOOD_CLICK,1,1.5
  - BIRCH_WOOD_STAIRS,WOOD_CLICK,1,1.5
  - JUNGLE_WOOD_STAIRS,WOOD_CLICK,1,1.5
  - COBBLE_WALL,DIG_GRAVEL,1,0.5
  - QUARTZ_ORE,DIG_STONE,1,1.3
  - QUARTZ_BLOCK,DIG_STONE,1,1.2
  - QUARTZ_STAIRS,DIG_STONE,1,1.2
  - STAINED_CLAY,DIG_STONE,1,0.7
  - LOG_2,DIG_WOOD,1,1.2
  - ACACIA_STAIRS,WOOD_CLICK,1,1.5
  - DARK_OAK_STAIRS,WOOD_CLICK,1,1.5
  - PRISMARINE,COW_WALK,1,0.5
  - SEA_LANTERN,COW_WALK,1,0.7
  - HAY_BLOCK,DIG_GRASS,1,1.5
  - HARD_CLAY,DIG_STONE,1,0.7
  - COAL_BLOCK,FALL_SMALL,1,0.7
  - PACKED_ICE,GLASS,1,0.5
  - RED_SANDSTONE,STEP_STONE,1,0.5
  - RED_SANDSTONE_STAIRS,STEP_STONE,1,0.5
  - STONE_SLAB2,STEP_STONE,1,0.5
  - SAPLING,STEP_GRASS,1,0.5
  - LEAVES,FIZZ,1,1.5
  - WEB,SPIDER_WALK,1,1.5
  - LONG_GRASS,STEP_GRASS,1,0.7
  - DEAD_BUSH,STEP_GRASS,1,1.2
  - YELLOW_FLOWER,STEP_GRASS,1,0.7
  - RED_ROSE,STEP_GRASS,1,0.7
  - BROWN_MUSHROOM,ITEM_PICKUP,1,0.5
  - RED_MUSHROOM,ITEM_PICKUP,1,0.5
  - TORCH,WOOD_CLICK,1,0.7
  - CHEST,STEP_LADDER,1,0.5
  - WORKBENCH,CHEST_OPEN,1,0.5
  - FURNACE,HORSE_LAND,1,0.5
  - LADDER,STEP_LADDER,1,1.2
  - SNOW,DIG_SNOW,1,1.2
  - CACTUS,STEP_WOOD,1,0.5
  - JUKEBOX,NOTE_SNARE_DRUM,1,1.2
  - FENCE,DIG_WOOD,1,1.5
  - MONSTER_EGGS,STEP_STONE,1,1.2
  - IRON_FENCE,ANVIL_LAND,1,0.6
  - THIN_GLASS,GLASS,1,1.5
  - VINE,STEP_GRASS,1,0.7
  - WATER_LILY,STEP_GRASS,1,0.7
  - NETHER_FENCE,DIG_STONE,1,0.5
  - ENCHANTMENT_TABLE,LEVEL_UP,1,0.5
  - ENDER_PORTAL_FRAME,ENDERMAN_TELEPORT,1,0.7
  - ENDER_CHEST,ENDERMAN_TELEPORT,1,1.5
  - ANVIL,ANVIL_LAND,1,1.5
  - TRAPPED_CHEST,STEP_LADDER,1,0.5
  - STAINED_GLASS_PANE,GLASS,1,1.5
  - LEAVES_2,FIZZ,1,1.5
  - SLIME_BLOCK,SLIME_WALK,1,0.5
  - CARPET,DIG_WOOL,1,1.5
  - DOUBLE_PLANT,STEP_GRASS,1,0.7
  - SPRUCE_FENCE,DIG_WOOD,1,1.5
  - BIRCH_FENCE,DIG_WOOD,1,1.5
  - JUNGLE_FENCE,DIG_WOOD,1,1.5
  - DARK_OAK_FENCE,DIG_WOOD,1,1.5
  - ACACIA_FENCE,DIG_WOOD,1,1.5
  - PAINTING,STEP_WOOD,1,1.2
  - SIGN,STEP_WOOD,1,1.2
  - BED,STEP_LADDER,1,0.7
  - ITEM_FRAME,ENDERDRAGON_WINGS,1,1.2
  - FLOWER_POT_ITEM,STEP_STONE,1,1.5
  - SKULL_ITEM,WITHER_HURT,1,0.5
  - ARMOR_STAND,ITEM_BREAK,1,0.8
  - BANNER,ENDERDRAGON_WINGS,1,0.5
  - DISPENSER,HORSE_LAND,1,0.7
  - NOTE_BLOCK,NOTE_SNARE_DRUM,1,1.5
  - PISTON_STICKY_BASE,PISTON_EXTEND,1,1.5
  - PISTON_BASE,PISTON_EXTEND,1,1.5
  - TNT,DIG_SAND,1,0.5
  - LEVER,CLICK,1,0.6
  - STONE_PLATE,CLICK,1,0.7
  - WOOD_PLATE,CLICK,1,0.8
  - REDSTONE_TORCH_ON,DIG_WOOD,1,1.5
  - STONE_BUTTON,CLICK,1,0.7
  - TRAP_DOOR,CLICK,1,0.5
  - FENCE_GATE,DOOR_OPEN,1,1.5
  - REDSTONE_LAMP_OFF,ITEM_BREAK,1,1.5
  - TRIPWIRE_HOOK,CLICK,1,0.6
  - WOOD_BUTTON,CLICK,1,0.8
  - GOLD_PLATE,ZOMBIE_METAL,1,1.4
  - IRON_PLATE,ZOMBIE_METAL,1,1.4
  - DAYLIGHT_DETECTOR,STEP_WOOD,1,0.7
  - REDSTONE_BLOCK,ITEM_BREAK,1,0.5
  - HOPPER,ZOMBIE_METAL,1,0.7
  - DROPPER,HORSE_LAND,1,0.7
  - IRON_TRAPDOOR,ZOMBIE_METAL,1,1.3
  - SPRUCE_FENCE_GATE,DOOR_OPEN,1,1.5
  - BIRCH_FENCE_GATE,DOOR_OPEN,1,1.5
  - JUNGLE_FENCE_GATE,DOOR_OPEN,1,1.5
  - DARK_OAK_FENCE_GATE,DOOR_OPEN,1,1.5
  - ACACIA_FENCE_GATE,DOOR_OPEN,1,1.5
  - WOOD_DOOR,DOOR_OPEN,1,0.5
  - IRON_DOOR,ZOMBIE_METAL,1,0.8
  - REDSTONE,FUSE,1,1.5
  - DIODE,DIG_WOOD,1,1.5
  - REDSTONE_COMPARATOR,DIG_WOOD,1,1.5
  - SPRUCE_DOOR_ITEM,DOOR_OPEN,1,0.5
  - BIRCH_DOOR_ITEM,DOOR_OPEN,1,0.5
  - JUNGLE_DOOR_ITEM,DOOR_OPEN,1,0.5
  - ACACIA_DOOR_ITEM,DOOR_OPEN,1,0.5
  - DARK_OAK_DOOR_ITEM,DOOR_OPEN,1,0.5
  - POWERED_RAIL,SKELETON_HURT,1,1.2
  - DETECTOR_RAIL,SKELETON_HURT,1,1.2
  - RAILS,SKELETON_HURT,1,1.2
  - ACTIVATOR_RAIL,SKELETON_HURT,1,1.2
  - MINECART,ITEM_BREAK,1,0.5
  - SADDLE,HORSE_SADDLE,1,1.5
  - BOAT,HORSE_WOOD,1,0.5
  - STORAGE_MINECART,ITEM_BREAK,1,0.5
  - POWERED_MINECART,ITEM_BREAK,1,0.5
  - CARROT_STICK,SHOOT_ARROW,1,1.5
  - EXPLOSIVE_MINECART,ITEM_BREAK,1,0.5
  - HOPPER_MINECART,ITEM_BREAK,1,0.5
  - BEACON,LEVEL_UP,1,1.2
  - BUCKET,ANVIL_LAND,1,0.6
  - WATER_BUCKET,WATER,1,1.5
  - LAVA_BUCKET,LAVA,1,1.5
  - SNOW_BALL,DIG_SNOW,1,1.5
  - MILK_BUCKET,WATER,1,1.5
  - PAPER,IRONGOLEM_THROW,1,0.7
  - BOOK,IRONGOLEM_THROW,1,0.5
  - SLIME_BALL,SLIME_WALK,1,1.5
  - BONE,SKELETON_IDLE,1,1.5
  - ENDER_PEARL,LEVEL_UP,1,0.7
  - EYE_OF_ENDER,LEVEL_UP,1,0.8
  - MONSTER_EGG,ORB_PICKUP,1,1.5
  - EXP_BOTTLE,LEVEL_UP,1,1.2
  - FIREBALL,EXPLODE,1,1.5
  - BOOK_AND_QUILL,IRONGOLEM_THROW,1,0.5
  - EMPTY_MAP,IRONGOLEM_THROW,1,0.7
  - FIREWORK_CHARGE,CREEPER_DEATH,1,1.2
  - IRON_BARDING,HORSE_ARMOR,1,1.5
  - GOLD_BARDING,HORSE_ARMOR,1,1.5
  - DIAMOND_BARDING,HORSE_ARMOR,1,1.5
  - GOLD_RECORD,CLICK,1,1.2
  - GREEN_RECORD,CLICK,1,1.2
  - RECORD_3,BAT_IDLE,1,0.5
  - RECORD_4,BAT_IDLE,1,0.6
  - RECORD_5,BAT_IDLE,1,0.7
  - RECORD_6,BAT_IDLE,1,0.8
  - RECORD_7,BAT_IDLE,1,0.9
  - RECORD_8,BAT_IDLE,1,1.1
  - RECORD_9,BAT_IDLE,1,1.2
  - RECORD_10,BAT_IDLE,1,1.3
  - RECORD_11,BAT_IDLE,1,1.4
  - RECORD_12,BAT_IDLE,1,1.5
  - APPLE,BURP,1,1.5
  - MUSHROOM_SOUP,SHEEP_WALK,1,1.5
  - BREAD,SHEEP_WALK,1,1.2
  - PORK,MAGMACUBE_WALK,1,1.5
  - GRILLED_PORK,ZOMBIE_WALK,1,1.5
  - GOLDEN_APPLE,ORB_PICKUP,1,0.5
  - RAW_FISH,MAGMACUBE_WALK2,1,1.5
  - COOKED_FISH,ZOMBIE_WALK,1,1.2
  - CAKE,SHEEP_WALK,1,0.5
  - COOKIE,SHEEP_WALK,1,1.2
  - MELON,BURP,1,1.5
  - RAW_BEEF,MAGMACUBE_WALK,1,1.5
  - COOKED_BEEF,ZOMBIE_WALK,1,1.5
  - RAW_CHICKEN,MAGMACUBE_WALK,1,1.5
  - COOKED_CHICKEN,ZOMBIE_WALK,1,1.5
  - ROTTEN_FLESH,ZOMBIE_WALK,1,0.5
  - SPIDER_EYE,ZOMBIE_WALK,1,0.7
  - CARROT_ITEM,BURP,1,1.5
  - POTATO_ITEM,BURP,1,1.5
  - BAKED_POTATO,SHEEP_WALK,1,0.7
  - POISONOUS_POTATO,BURP,1,1.5
  - PUMPKIN_PIE,SHEEP_WALK,1,1.2
  - RABBIT,MAGMACUBE_WALK,1,1.5
  - COOKED_RABBIT,ZOMBIE_WALK,1,1.5
  - RABBIT_STEW,SHEEP_WALK,1,1.5
  - MUTTON,MAGMACUBE_WALK,1,1.5
  - COOKED_MUTTON,ZOMBIE_WALK,1,1.5
  - IRON_SPADE,ANVIL_LAND,1,0.6
  - IRON_PICKAXE,ANVIL_LAND,1,0.6
  - IRON_AXE,ANVIL_LAND,1,0.6
  - FLINT_AND_STEEL,FIRE_IGNITE,1,0.5
  - WOOD_SPADE,WOOD_CLICK,1,0.5
  - WOOD_PICKAXE,WOOD_CLICK,1,0.5
  - WOOD_AXE,WOOD_CLICK,1,0.5
  - STONE_SPADE,FALL_BIG,1,0.5
  - STONE_PICKAXE,FALL_BIG,1,0.5
  - STONE_AXE,FALL_BIG,1,0.5
  - DIAMOND_SPADE,ANVIL_LAND,1,1.2
  - DIAMOND_PICKAXE,ANVIL_LAND,1,1.2
  - DIAMOND_AXE,ANVIL_LAND,1,1.2
  - GOLD_SPADE,ANVIL_LAND,1,0.5
  - GOLD_PICKAXE,ANVIL_LAND,1,0.5
  - GOLD_AXE,ANVIL_LAND,1,0.5
  - WOOD_HOE,WOOD_CLICK,1,0.5
  - STONE_HOE,FALL_BIG,1,0.5
  - IRON_HOE,ANVIL_LAND,1,0.6
  - DIAMOND_HOE,ANVIL_LAND,1,1.2
  - GOLD_HOE,ANVIL_LAND,1,0.5
  - COMPASS,HURT_FLESH,1,1.5
  - FISHING_ROD,SHOOT_ARROW,1,1.5
  - WATCH,HURT_FLESH,1,1.2
  - SHEARS,SHEEP_SHEAR,1,1.5
  - LEASH,STEP_SAND,1,0.5
  - NAME_TAG,FIRE_IGNITE,1,1.5
  - ENCHANTED_BOOK,HORSE_SADDLE,1,1.3
  - BOW,ARROW_HIT,1,0.6
  - ARROW,STEP_LADDER,1,1.5
  - IRON_SWORD,ANVIL_LAND,1,0.6
  - WOOD_SWORD,WOOD_CLICK,1,0.5
  - STONE_SWORD,FALL_BIG,1,0.5
  - DIAMOND_SWORD,ANVIL_LAND,1,1.2
  - GOLD_SWORD,ANVIL_LAND,1,0.5
  - LEATHER_HELMET,FALL_BIG,1,0.7
  - LEATHER_CHESTPLATE,FALL_BIG,1,0.7
  - LEATHER_LEGGINGS,FALL_BIG,1,0.7
  - LEATHER_BOOTS,FALL_BIG,1,0.7
  - CHAINMAIL_HELMET,HORSE_ARMOR,1,0.7
  - CHAINMAIL_CHESTPLATE,HORSE_ARMOR,1,0.7
  - CHAINMAIL_LEGGINGS,HORSE_ARMOR,1,0.7
  - CHAINMAIL_BOOTS,HORSE_ARMOR,1,0.7
  - IRON_HELMET,BLAZE_HIT,1,0.7
  - IRON_CHESTPLATE,BLAZE_HIT,1,0.7
  - IRON_LEGGINGS,BLAZE_HIT,1,0.7
  - IRON_BOOTS,BLAZE_HIT,1,0.7
  - DIAMOND_HELMET,BLAZE_HIT,1,0.5
  - DIAMOND_CHESTPLATE,BLAZE_HIT,1,0.5
  - DIAMOND_LEGGINGS,BLAZE_HIT,1,0.5
  - DIAMOND_BOOTS,BLAZE_HIT,1,0.5
  - GOLD_HELMET,BLAZE_HIT,1,0.7
  - GOLD_CHESTPLATE,BLAZE_HIT,1,0.7
  - GOLD_LEGGINGS,BLAZE_HIT,1,0.7
  - GOLD_BOOTS,BLAZE_HIT,1,0.7
  - GHAST_TEAR,LEVEL_UP,1,1.5
  - POTION,SWIM,1,1.5
  - GLASS_BOTTLE,GLASS,1,1.5
  - FERMENTED_SPIDER_EYE,SLIME_ATTACK,1,1.5
  - BLAZE_POWDER,LEVEL_UP,1,1.3
  - MAGMA_CREAM,MAGMACUBE_WALK2,1,1.2
  - BREWING_STAND_ITEM,ITEM_BREAK,1,1.5
  - CAULDRON_ITEM,ANVIL_LAND,1,1.5
  - SPECKLED_MELON,ORB_PICKUP,1,0.5
  - GOLDEN_CARROT,ORB_PICKUP,1,0.5
  - RABBIT_FOOT,STEP_WOOL,1,1.5
  - COAL,CHICKEN_WALK,1,0.5
  - DIAMOND,ORB_PICKUP,1,0.8
  - IRON_INGOT,ZOMBIE_METAL,1,1.5
  - GOLD_INGOT,ZOMBIE_METAL,1,1.5
  - STICK,WOOD_CLICK,1,1.2
  - BOWL,WOOD_CLICK,1,1.2
  - STRING,DIG_SAND,1,1.2
  - FEATHER,DIG_SAND,1,1.5
  - SULPHUR,CREEPER_DEATH,1,1.5
  - SEEDS,STEP_SAND,1,1.2
  - WHEAT,DIG_GRASS,1,1.5
  - FLINT,FIRE_IGNITE,1,0.7
  - LEATHER,STEP_WOOL,1,1.2
  - CLAY_BRICK,STEP_STONE,1,1.5
  - CLAY_BALL,STEP_SAND,1,0.8
  - SUGAR_CANE,STEP_GRASS,1,0.6
  - EGG,CHICKEN_EGG_POP,1,0.7
  - GLOWSTONE_DUST,LEVEL_UP,1,1.4
  - INK_SACK,STEP_SAND,1,1.5
  - SUGAR,STEP_GRASS,1,1.3
  - PUMPKIN_SEEDS,STEP_SAND,1,1.2
  - MELON_SEEDS,STEP_SAND,1,1.2
  - BLAZE_ROD,BLAZE_HIT,1,1.5
  - GOLD_NUGGET,CHICKEN_WALK,1,0.7
  - NETHER_STALK,EAT,1,1.5
  - EMERALD,ORB_PICKUP,1,1.2
  - NETHER_STAR,LEVEL_UP,1,1.2
  - NETHER_BRICK_ITEM,DIG_STONE,1,0.6
  - QUARTZ,DIG_STONE,1,1.3
  - PRISMARINE_SHARD,LAVA_POP,1,1.5
  - PRISMARINE_CRYSTALS,LAVA_POP,1,1.5
  - RABBIT_HIDE,STEP_WOOL,1,1.5